COLLECTION_PORTFOLIOS = "portfolios"
COLLECTION_PROGRAMMES = "programmes"
COLLECTION_CURRENCY_TABLES = "currencyTables"
COLLECTION_ANALYSES = "lossallocation"
COLLECTION_EVENTS = "scenarios"
COLLECTION_SIZES = "sizes"
COLLECTION_CALCULATIONS = "calculations"

CALCULATIONS_LOGIC = "calculations/logic/"

ENDPOINT_PORTFOLIO_UPLOADS = "portfolio_uploads"

ENDPOINT_PORTFOLIO_DOWNLOAD = CALCULATIONS_LOGIC + "portfoliodownload/{portfolio}"
ENDPOINT_DICTIONARY = CALCULATIONS_LOGIC + "dictionary"
ENDPOINT_NODE_METRICS = CALCULATIONS_LOGIC + "nodemetrics"
ENDPOINT_CALC_NODE_METRICS = CALCULATIONS_LOGIC + "nodemetrics/{portfolio}"
ENDPOINT_CALC_ANALYSIS_PARAMETERS = CALCULATIONS_LOGIC + "laparams/{portfolio}"
ENDPOINT_PROPERTIES = CALCULATIONS_LOGIC + "properties"
ENDPOINT_CALC_CONNECTED_NODES = CALCULATIONS_LOGIC + "connectednodes/{portfolio}"
ENDPOINT_PROGRAMMES = CALCULATIONS_LOGIC + "programmes"

ENDPOINT_CLAIMS = "calculations/logic/{{calculations_id}}/logs/claims/{level}"
ENDPOINT_LOGS = "calculations/logic/{calculations_id}/logs/logs"
ENDPOINT_GRAPH = "calculations/logic/{calculations_id}/logs/graph"
PORT = "port"

AUTH_SERVER = "auth_server"
ISSUER = "issuer"
AUDIENCE = "audience"
CLIENT_ID = "client_id"
CLIENT_SECRET = "client_secret"
AUTHORIZATION_URL = "authorization_url"
TOKEN_URL = "token_url"
BASE_URI = "base_uri"
BASE_URI_PDCA = "base_uri_pdca"
REDIRECT_URI = "redirect_uri"
AUTHORIZATION_CODE = "authorization_code"
VERIFY_SSL = "verify_ssl"

ACCOUNT_NAME = "accountname"
ACCOUNT_NUMBER = "accountnumber"
HEADOFFICE_NAME = "headofficename"
HEADOFFICE_NUMBER = "headofficenumber"
POLICY_NAME = "policyname"
POLICY_NUMBER = "policynumber"
INSURER = "insurername"
POLICY_TYPE = "policytype"
CITY = "city"
STATE = "state"
COUNTY = "county"
COUNTRY = "country"
JURISDICTION = "jurisdiction"
REINSURANCE_PROGRAMME = "programme"
INCEPTION_DATE = "inceptiondate"
EXPIRATION_DATE = "expirationdate"
POSTAL_CODE = "postalCode"
PAYROLL = "payroll"
TURNOVER = "turnover"
EMPLOYEE_COUNT = "employeecount"
PER_OCCURENCE_LIMIT = "limit"
AGGREGATE_LIMIT = "agglimit"
PREMIUM = "premium"
ATTACHMENT_POINT = "attachmentpointexcesspoint"
TRIGGER_TYPE = "typeofcover"
